# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Slides
version:      v0.0.2
version_from: lib/WWW/Slides.pm
installdirs:  site
requires:
    Carp:                          0
    Digest::MD5:                   0
    English:                       0
    HTTP::Response:                0
    IO::Handle:                    0
    IO::Select:                    0
    IO::Socket:                    0
    Object::InsideOut:             0
    Socket:                        0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
